### ISSUE TITLE
Redefinition of module 'CSr25519'

### ISSUE THREAD

**Issue by AKGupta31** [tesseract-one/sr25519.swift#1]
<img width="461" alt="Screenshot 2021-04-16 at 1 17 28 PM" src="https://user-images.githubusercontent.com/51131294/114990622-527b9780-9eb6-11eb-9a8e-7cc38a8b035b.png">
I am getting this error when i added the package

**Comment by ypopovych** [comment]
Hi. Can you, please, provide more details (SPM or CococaPods, platform, etc.)?

**Comment by AKGupta31** [comment]
I don't know how many ways are there to install the sdk but when i tried for cocoa pods it showed me
<img width="561" alt="Screenshot 2021-04-16 at 1 33 03 PM" src="https://user-images.githubusercontent.com/51131294/114992504-76d87380-9eb8-11eb-9f84-4eba0f5617a9.png">
And then i tried for swift package manager ....and now its showing the above error....

**Comment by ypopovych** [comment]
For CocoaPods use `0.0.4` as the version for now. I'm working on the library, will release 0.1 soon.

**Comment by AKGupta31** [comment]
Is there any way ...i can use this library by doing changes to my project or something else?

**Comment by AKGupta31** [comment]
@ypopovych Thanks So much i resolve it.
Just removed the version from Pod file and then pod install..Now working fine
